FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

ARG VERBOSE
COPY crosstool-ng.sh /
COPY cross-toolchains/docker/crosstool-config/aarch64-unknown-linux-gnu-cross.config /
RUN /crosstool-ng.sh aarch64-unknown-linux-gnu-cross.config 5

ENV PATH /x-tools/aarch64-unknown-linux-gnu/bin/:$PATH

COPY qemu.sh /
RUN /qemu.sh aarch64

COPY dropbear.sh /
RUN /dropbear.sh

COPY linux-image.sh /
RUN /linux-image.sh aarch64

COPY linux-runner /

ENV CARGO_TARGET_S390X_UNKNOWN_LINUX_GNU_LINKER=aarch64-unknown-linux-gnu-gcc \
    CARGO_TARGET_S390X_UNKNOWN_LINUX_GNU_RUNNER="/linux-runner aarch64" \
    CC_aarch64_unknown_linux_gnu=aarch64-unknown-linux-gnu-gcc \
    CXX_aarch64_unknown_linux_gnu=aarch64-unknown-linux-gnu-g++ \
    BINDGEN_EXTRA_CLANG_ARGS_arm_unknown_linux_gnueabihf="--sysroot=/x-tools/aarch64-unknown-linux-gnu/aarch64-unknown-linux-gnu/sysroot/" \
    QEMU_LD_PREFIX=/x-tools/aarch64-unknown-linux-gnu/aarch64-unknown-linux-gnu/sysroot/ \
    RUST_TEST_THREADS=1
